version: "3"

services:
  db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_DB=yitaoio
      - POSTGRES_USER=tinyx
      - POSTGRES_PASSWORD=tinyx

  server:
    image: hb1412/yitao.io:latest
    build: ./
    volumes:
      - ./:/code
    depends_on:
      - db
    ports:
      - "8000:8000"

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
