version: "3"

services:
  db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_DB=yitaoio
      - POSTGRES_USER=tinyx
      - POSTGRES_PASSWORD=tinyx

  server:
    image: hb1412/yitao.io:latest
    build: ./
    volumes:
      - ./:/code
    command: sh -c "dockerize -wait tcp://db:5432 && ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
