# Generated by Django 2.2.9 on 2020-11-18 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category_is_full_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_full_size',
            field=models.BooleanField(default=False, help_text='Should this category be rendered full sized.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='The name of the category', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_cn',
            field=models.CharField(blank=True, help_text='The name of the category', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='The order of this category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='annotation',
            field=models.TextField(blank=True, help_text='Write something to remind you which image this is', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(help_text='The category of this image', on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='The description that will appear under the image', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description_cn',
            field=models.TextField(blank=True, help_text='The description that will appear under the image', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=filer.fields.image.FilerImageField(help_text='The image file', max_length=5000, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(help_text='The name of the image', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0, help_text='The order of this image under the category'),
        ),
    ]
