# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('duedate', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolist_eventclass_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Class',
                'verbose_name_plural': 'Event Classes',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='eventclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.EventClass'),
        ),
    ]
