# Generated by Django 2.2.9 on 2020-01-17 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ifthen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='GUID of this move'),
        ),
    ]
